function init(self)
	msg.post(".", "acquire_input_focus")
	factory.create("#factory")
	timer.delay(1, true, function()
		factory.create("#factory")
	end)
end

function on_input(self, action_id, action)
	if action_id == hash("left") then
		local pos = go.get_position()
		pos.x = pos.x - 5
		go.set_position(pos)
		
	elseif action_id == hash("right") then
		local pos = go.get_position()
		pos.x = pos.x + 5
		go.set_position(pos)
	end
end